spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: true
      path: /h2
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/gs-jdbc
#    username: root
#    password: null
#    initialize: true

logging:
  level:
    com:
      example:
        bootweb:
          accessory: DEBUG